[workspace]
name = "ac-icon-navigator"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks.export]
cmd = "python scripts/export_data.py"
env = { KMP_DUPLICATE_LIB_OK = "TRUE" }

[tasks.embed]
cmd = "python scripts/embed.py --image_dir ./data/icons --output_dir ./data/embeddings"
env = { KMP_DUPLICATE_LIB_OK = "TRUE" }

[dependencies]
python = ">=3.10"
pip = "*"
pillow = "*"
matplotlib = "*"
numpy = "*"

[pypi-dependencies]
torch = ">=2.0"
transformers = "*"
