[workspace]
name = "ac-icon-navigator"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
export = "python export_data.py"
find = "python find.py"
filter-icons = "python filter_icons.py"
make-transparent = "python make_white_transparent.py"

[tasks.embed]
cmd = "python embed.py"
env = { KMP_DUPLICATE_LIB_OK = "TRUE" }
inputs = [{ file = "embeddings/embeddings.pt", missing = "allow" }]
outputs = [{ file = "embeddings/embeddings.pt", missing = "allow" }]

[dependencies]
python = ">=3.10"
pip = "*"
pillow = "*"
matplotlib = "*"
numpy = "*"

[pypi-dependencies]
torch = ">=2.0"
transformers = "*"
